components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/number-type/CARDINAL
        title: cardinale
      - const: http://publications.europa.eu/resource/authority/number-type/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/number-type/ORDINAL
        title: ordinale
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
