components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/case-report/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/case-report/REPORT_CASE_1
        title: "Raccolta generale \u2013 Corte di giustizia"
      - const: http://publications.europa.eu/resource/authority/case-report/REPORT_CASE_2
        title: "Raccolta generale \u2013 Tribunale"
      - const: http://publications.europa.eu/resource/authority/case-report/REPORT_CASE_STAFF
        title: Raccolta della funzione pubblica
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
