components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/ACO
        title: Diploma di Accademia di Belle Arti, Danza, Arte Drammatica, ISIA, ecc.
          Conservatorio (vecchio ordinamento)
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/CDU
        title: Diploma universitario di due/tre anni, Scuola diretta a fini speciali,
          altro diploma terziario non universitario
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/FLA
        title: Diploma accademico di Alta Formazione Artistica, Musicale e Coreutica
          di I livello
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/IFP
        title: Attestato IFP di qualifica professionale triennale (operatore)/Diploma
          professionale IFP di tecnico (quarto anno) (dal 2005)
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/IFTS
        title: Certificato di specializzazione tecnica superiore IFTS (dal 2000)
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/ITS
        title: Diploma di tecnico superiore ITS (corsi biennali) (dal 2013)
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/L
        title: 'Laurea di primo livello '
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/LD
        title: Laurea specialistica/magistrale a ciclo unico o diploma di laurea di
          4-6 anni
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/LS
        title: Laurea specialistica/magistrale biennale
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/LSE
        title: Licenza media o avviamento professionale (conseguito non oltre l'anno
          1965) /Diploma di Istruzione secondaria di I grado
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/NED
        title: Nessun titolo di studio
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/PSE
        title: Licenza elementare/ Attestato di valutazione finale
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/RDD
        title: 'Dottorato di ricerca/Diploma accademico di formazione alla ricerca '
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/SLA
        title: Diploma accademico di Alta Formazione Artistica, Musicale e Coreutica
          di II livello
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/USG
        title: "Diploma di maturit\xE0 / diploma di istruzione secondaria di II grado\
          \ di 4-5 anni (che permette l\u2019iscrizione all\u2019universit\xE0)"
      - const: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/USV
        title: "Diploma di qualifica professionale di scuola secondaria di II grado\
          \ di 2-3 anni (che non permette l\u2019iscrizione all\u2019Universit\xE0\
          )"
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
