components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/applicability/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/applicability/no
        title: 'No'
      - const: http://publications.europa.eu/resource/authority/applicability/not-known
        title: Non ancora noto
      - const: http://publications.europa.eu/resource/authority/applicability/yes
        title: "S\xEC"
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
