#
# This schema is in OpenAPI 3.0 format
#   and can be referred via #/components/schemas/Money
#
openapi: 3.0.3
info:
  title: The Money schema
  version: 202201.00.00
  x-summary: A minimal Money schema.
  license:
    name: BSD3
    url: https://opensource.org/licenses/BSD-3-Clause
  termsOfService: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: Roberto Polli
    email: robipolli@gmail.com
    url: http://spcdata.digitpa.gov.it/Amministrazione/agid
  description: |-
    This Money schema is associated to the  [POT](https://ontopia-lodview.agid.gov.it/onto/POT) ontology
    of prices, offers and tickets.

    This description field can be rendered in markdown or in text-only in catalogues
    and other interfaces.
paths: {}
servers: []
tags: []
components:
  schemas:
    CurrencyCode:
      description: |
        Specifies the currency of the amount or of the account.
        A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".
      example: EUR
      pattern: ^[A-Z]{3,3}$
      type: string
      default: EUR
    Amount:
      description: |
        ISO20022: Amount of money to be moved between the debtor and creditor, before deduction of charges, expressed in the currency as ordered by the initiating party.
      example: '12.25'
      pattern: ^\-{0,1}[0-9]{1,13}(\.[0-9]{0,5}){0,1}$
      type: string
    Money:
      x-jsonld-context:
        amount:
          "@id": "https://w3id.org/italia/onto/POT/hasCurrencyValue"
        currency:
          "@id": "https://w3id.org/italia/onto/POT/hasCurrency"
          "@type": "@id"
          "@context":
            "@base": "https://publications.europa.eu/resource/authority/currency"
      additionalProperties: false
      description: |
        An amount of money in a given currency.
      example:
        amount: '12.25'
        currency: EUR
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        currency:
          $ref: '#/components/schemas/CurrencyCode'
      required:
      - currency
      - amount
      type: object
    Exports:
      anyOf:
      - $ref: "#/components/schemas/Money"
