components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/additional
        title: "Necessit\xE0 di ulteriori lavori o servizi eseguiti dall'appaltatore\
          \ originale"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/artistic
        title: "L'appalto pu\xF2 essere eseguito solo da un particolare operatore\
          \ economico in quanto consiste nella creazione o nell'acquisizione di un'opera\
          \ d'arte o rappresentazione artistica unica"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/bargain
        title: "Acquisti d'opportunit\xE0, approfittando di un'occasione particolarmente\
          \ vantaggiosa ma di breve durata, a prezzo sensibilmente inferiore ai prezzi\
          \ normalmente praticati sul mercato"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/below-thres
        title: "Appalti il cui valore stimato \xE8 inferiore alle soglie relative\
          \ agli appalti"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/below-thres-sme
        title: .nan
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/closure
        title: "Acquisto a condizioni particolarmente vantaggiose, da un fornitore\
          \ che cessa definitivamente l'attivit\xE0 commerciale"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/commodity
        title: Appalto di forniture quotate e acquistate sul mercato delle materie
          prime
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/contest
        title: Appalto di servizi che deve essere aggiudicato al vincitore o ad uno
          dei vincitori secondo le regole di un concorso di progettazione
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/crisis
        title: "L'urgenza risultante da situazioni di crisi non \xE8 compatibile con\
          \ i termini previsti dalla procedura ristretta e dalla procedura negoziata\
          \ con pubblicazione di un bando di gara"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/defse-excl
        title: Esclusioni specifiche nei settori della difesa e della sicurezza
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/dir24-list
        title: Appalti elencati nella direttiva 2014/24/UE, articolo 7, ma non rientranti
          nell'ambito della direttiva 2014/25/UE
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/dir81-annexii
        title: L'appalto rientra nell'elenco dei servizi di cui all'allegato II della
          direttiva 2009/81/CE
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/dir81-transport
        title: Appalti aventi per oggetto servizi di trasporto aereo e marittimo per
          le forze armate di uno Stato membro di stanza o che devono essere stanziate
          all'estero, conformemente alle rigorose condizioni fissate dalla direttiva
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/ecom-excl
        title: Esclusione specifica nel settore delle comunicazioni elettroniche
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/energy-supply
        title: Appalti aggiudicati per la fornitura di energia o di combustibili destinati
          alla produzione di energia
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/exclusive
        title: "L'appalto pu\xF2 essere eseguito solo da un particolare operatore\
          \ economico per motivi di tutela di diritti esclusivi, inclusi i diritti\
          \ di propriet\xE0 intellettuale"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/existing
        title: Rinnovo parziale o ampliamento di forniture o impianti esistenti realizzati
          dal fornitore originario, commissionati conformemente alle rigorose condizioni
          fissate dalla direttiva
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/in-house
        title: "Appalto pubblico tra enti nell'ambito del settore pubblico (appalto\
          \ \xABin-house\xBB), appalti aggiudicati a imprese collegate o appalti aggiudicati\
          \ a una joint-venture o nell'ambito di una joint-venture"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/int-oper
        title: .nan
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/int-rules
        title: Procedura organizzata in base a norme internazionali
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/irregular
        title: In esito a un avviso o bando precedente sono pervenute solo offerte
          non regolari o inaccettabili. Sono stati ammessi alla procedura negoziata
          unicamente tutti gli offerenti della procedura precedente che hanno soddisfatto
          i criteri di selezione, non sono ricaduti in cause di esclusione e hanno
          soddisfatto i requisiti formali
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/liquidator
        title: Acquisto a condizioni particolarmente vantaggiose, dal curatore o liquidatore
          di un fallimento, di un concordato giudiziario o di una procedura analoga
          prevista nelle legislazioni o regolamentazioni nazionali
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/non-buyer-aw
        title: Contratti aggiudicati da parti che non sono committenti
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/non-contr
        title: Determinati casi di natura extracontrattuale
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/non-p-int
        title: Contratti non a titolo oneroso
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/not-wss
        title: Contratti non aventi per oggetto l'esecuzione di lavori, la fornitura
          di prodotti o la prestazione di servizi
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/other-activity
        title: "Appalti aggiudicati per fini diversi dal perseguimento di un'attivit\xE0\
          \ interessata o per l'esercizio di un'attivit\xE0 in un paese terzo"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/other-exclusive
        title: "L'appalto pu\xF2 essere eseguito solo da un particolare operatore\
          \ economico per motivi di tutela di altri diritti esclusivi, inclusi i diritti\
          \ di propriet\xE0 intellettuale, diversi da quelli definiti dalla direttiva\
          \ 2014/23/UE, articolo 5, paragrafo 10"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/rail
        title: .nan
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/rd
        title: L'appalto riguarda servizi di ricerca e sviluppo diversi da quelli
          di cui alla direttiva 2009/81/CE, articolo 13
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/repetition
        title: Nuovi lavori o servizi consistenti nella ripetizione di lavori o servizi
          analoghi, commissionati conformemente alle rigorose condizioni fissate dalla
          direttiva
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/resd
        title: L'oggetto dell'appalto riguarda unicamente scopi di ricerca, di sperimentazione,
          di studio o di sviluppo alle condizioni della direttiva
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/rl-third
        title: Appalti aggiudicati a scopo di rivendita o di locazione a terzi
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/sc-right
        title: Appalto di servizio aggiudicato in base a un diritto esclusivo
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/serv-excl
        title: Esclusioni specifiche per gli appalti di servizi
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/spe-arrang
        title: "Attivit\xE0 direttamente esposte alla concorrenza e appalti soggetti\
          \ a disposizioni specifiche"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/technical
        title: "L'appalto pu\xF2 essere eseguito solo da un particolare operatore\
          \ economico a causa dell'assenza di concorrenza per motivi tecnici"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/tra-ser
        title: Concessioni di servizi di trasporto aereo sulla base di una licenza
          di gestione a norma del regolamento (CE) n. 1008/2008 del Parlamento europeo
          e del Consiglio o concessioni di servizi di trasporto pubblico di passeggeri
          ai sensi del regolamento (CE) n. 1370/2007
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/unsuitable
        title: "Non \xE8 stata presentata alcuna offerta appropriata, n\xE9 alcuna\
          \ domanda di partecipazione o candidatura appropriata in esito a un avviso\
          \ o bando precedente"
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/urgency
        title: Ragioni di estrema urgenza derivanti da eventi imprevedibili dal committente
      - const: http://publications.europa.eu/resource/authority/direct-award-justification/water-purch
        title: Appalti aggiudicati per l'acquisto di acqua
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
