components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/asset-classification/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_1fb7be39
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_230aaab7
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_25e514f4
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_2db4690d
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_32ffe82d
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_35dcf03c
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_3626c85a
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_366e3b24
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_3948c2ed
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_5796a20b
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_5b130cc6
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_638e1719
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_64714767
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_722cef3f
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_89b4bdb7
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_8da81c02
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_a2df28a1
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_a6822084
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_a7773248
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_b0bfba6e
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_b37963b3
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_b81ceeea
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_bba2bb35
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_c0b5956c
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_c2f98e5f
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_c2ffe197
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_cdd11291
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_d3bf7907
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_d5c26195
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_d9dd5715
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_e4cf092c
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_ebfb658e
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_ecacbeba
        title: .nan
      - const: http://publications.europa.eu/resource/authority/asset-classification/c_eed252ff
        title: .nan
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
