components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf: []
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
