components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/capital-classification/CAP_COU
        title: .nan
      - const: http://publications.europa.eu/resource/authority/capital-classification/CAP_NON
        title: .nan
      - const: http://publications.europa.eu/resource/authority/capital-classification/OP_DATPRO
        title: Dati provvisori
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
