components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/role-nature/ENTITY
        title: .nan
      - const: http://publications.europa.eu/resource/authority/role-nature/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/role-nature/PERSON
        title: .nan
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
