components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/contract-nature/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/contract-nature/combined
        title: Appalti misti
      - const: http://publications.europa.eu/resource/authority/contract-nature/services
        title: Servizi
      - const: http://publications.europa.eu/resource/authority/contract-nature/supplies
        title: Forniture
      - const: http://publications.europa.eu/resource/authority/contract-nature/works
        title: Lavori
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
