components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/distribution-type/DOWNLOADABLE_FILE
        title: File scaricabile
      - const: http://publications.europa.eu/resource/authority/distribution-type/FEED_INFO
        title: Feed di informazioni
      - const: http://publications.europa.eu/resource/authority/distribution-type/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/distribution-type/VISUALIZATION
        title: Visualizzazione
      - const: http://publications.europa.eu/resource/authority/distribution-type/WEB_SERVICE
        title: Servizio web/API
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
