components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/case-status/CLOSED
        title: Causa conclusa
      - const: http://publications.europa.eu/resource/authority/case-status/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/case-status/PROGRESS
        title: Causa pendente
      - const: http://publications.europa.eu/resource/authority/case-status/STAY
        title: .nan
      - const: http://publications.europa.eu/resource/authority/case-status/WITHDRAW
        title: .nan
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
