components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/position-type/CONTR
        title: contrattuale
      - const: http://publications.europa.eu/resource/authority/position-type/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/position-type/OTHER
        title: altro
      - const: http://publications.europa.eu/resource/authority/position-type/PERM
        title: permanente
      - const: http://publications.europa.eu/resource/authority/position-type/SNE
        title: esperto nazionale distaccato
      - const: http://publications.europa.eu/resource/authority/position-type/TEMP
        title: temporaneo
      - const: http://publications.europa.eu/resource/authority/position-type/TRAINEE
        title: tirocinante
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
