components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/human-sex/FEMALE
        title: femminile
      - const: http://publications.europa.eu/resource/authority/human-sex/MALE
        title: maschile
      - const: http://publications.europa.eu/resource/authority/human-sex/NAP
        title: non pertinente
      - const: http://publications.europa.eu/resource/authority/human-sex/NKN
        title: ignoto
      - const: http://publications.europa.eu/resource/authority/human-sex/NST
        title: non dichiarato
      - const: http://publications.europa.eu/resource/authority/humansexes/OP_DATPRO
        title: Dati provvisori
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
