components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/eu-budget-status/CONT
        title: Prosecuzione
      - const: http://publications.europa.eu/resource/authority/eu-budget-status/NEW
        title: Nuovo
      - const: http://publications.europa.eu/resource/authority/eu-budget-status/OP_DATPRO
        title: Dati provvisori
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
