components:
  schemas:
    MyVocabulary:
      description: A schema containing all the vocabulary terms.
      oneOf:
      - const: http://publications.europa.eu/resource/authority/grammatical-gender/F
        title: Femminile
      - const: http://publications.europa.eu/resource/authority/grammatical-gender/G
        title: .nan
      - const: http://publications.europa.eu/resource/authority/grammatical-gender/M
        title: Maschile
      - const: http://publications.europa.eu/resource/authority/grammatical-gender/N
        title: Neutro
      - const: http://publications.europa.eu/resource/authority/grammatical-gender/OP_DATPRO
        title: Dati provvisori
      - const: http://publications.europa.eu/resource/authority/grammatical-gender/U
        title: Comune
      - const: http://publications.europa.eu/resource/authority/grammatical-gender/Z
        title: .nan
info:
  contact:
    name: Vocabulary
    url: https://foo.bar
  title: Vocabulary
  version: 1.0.0
  x-summary: Vocabulary
openapi: 3.0.0
